books_list = ['Genesis',
    'Exodus',
    'Leviticus',
    'Numbers',
    'Deuteronomy',
    'Joshua',
    'Judges',
    'Ruth',
    '1st-Samuel',
    '2nd-Samuel',
    '1st-Kings',
    '2nd-Kings',
    '1st-Chronicles',
    '2nd-Chronicles',
    'Ezra',
    'Nehemiah',
    'Esther',
    'Job',
    'Psalms',
    'Proverbs',
    'Ecclesiastes',
    'Song-of-Solomon',
    'Isaiah',
    'Jeremiah',
    'Lamentations',
    'Ezekiel',
    'Daniel',
    'Hosea',
    'Joel',
    'Amos',
    'Obadiah',
    'Jonah',
    'Micah',
    'Nahum',
    'Habakkuk',
    'Zephaniah',
    'Haggai',
    'Zechariah',
    'Malachi',
    'Matthew',
    'Mark',
    'Luke',
    'John',
    'Acts',
    'Romans',
    '1st-Corinthians',
    '2nd-Corinthians',
    'Galatians',
    'Ephesians',
    'Philippians',
    'Colossians',
    '1st-Thessalonians',
    '2nd-Thessalonians',
    '1st-Timothy',
    '2nd-Timothy',
    'Titus',
    'Philemon',
    'Hebrews',
    'James',
    '1st-Peter',
    '2nd-Peter',
    '1st-John',
    '2nd-John',
    '3rd-John',
    'Jude',
    'Revelation']

"""https://www.logos.com/bible-book-abbreviations"""
complete_books_list = [
    'Genesis', 'Gen', 'GEN', 'Ge', 'Gn',
    'Exodus', 'Ex', 'Exo', 'Exod',
    'Leviticus', 'Lev', 'Le', 'Lv',
    'Numbers', 'Num', 'Nu', 'Nm', 'Nb',
    'Deuteronomy', 'Deut', 'De', 'Dt',
    'Joshua', 'Josh', 'Jos', 'Jsh',
    'Judges', 'Judg', 'Jdg', 'Jdgs',
    'Ruth', 'Rth', 'Ru',
    '1st-Samuel', '1-Sam', '1-Sa', '1-S', 'I-Sam', 'I-Sa', '1Sam', '1Sa', '1S', '1-Samuel', '1st-Sam', 'First-Samuel', 'First-Sam',
    '2nd-Samuel', '2-Sam', '2-Sa', '2-S', 'II-Sam', 'II-Sa', '2Sam', '2Sa', '2S', '2-Samuel', '2nd-Sam', 'Second-Samuel', 'Second-Sam',
    '1st-Kings', '1-Kgs', '1-Ki', '1Kgs', '1Kin', '1Ki', '1K', 'I-Kgs', 'I-Ki', '1-Kings', '1st-Kgs', 'First-Kings', 'First-Kgs',
    '2nd-Kings', '2 Kgs', '2-Ki', '2Kgs', '2Kin', '2Ki', '2K', 'II-Kgs', 'II-Ki', '2-Kings', '2nd-Kgs', 'Second-Kings', 'Second-Kgs',
    '1st-Chronicles', '1-Chron', '1-Chr', '1-Ch', '1Chron', '1Chr', '1Ch', 'I-Chron', 'I-Chr', 'I-Ch', '1-Chronicles', '1st-Chron', 'First-Chronicles', 'First-Chron',
    '2nd-Chronicles','2-Chron', '2-Chr', '2-Ch', '2Chron', '2Chr', '2Ch', 'II-Chron', 'II-Chr', 'II-Ch', '2-Chronicles', '2nd-Chron', 'Second-Chronicles', 'Second-Chron',
    'Ezra', 'Ezr', 'Ez',
    'Nehemiah','Neh', 'Ne',
    'Esther', 'Est', 'Esth', 'Es',
    'Job', 'Jb',
    'Psalms', 'Ps', 'Psalm', 'Pslm', 'Psa', 'Psm', 'Pss',
    'Proverbs', 'Prov', 'Pro', 'Prv', 'Pr',
    'Ecclesiastes', 'Eccle', 'Ecc', 'Ec', 'Qoh',
    'Song-of-Solomon', 'Song', 'Song-of-Songs', 'SOS', 'So', 'Canticle-of-Canticles', 'Canticles', 'Cant', 
    'Isaiah', 'Isa', 'Is',
    'Jeremiah', 'Jer', 'Je', 'Jr',
    'Lamentations', 'Lam', 'La',
    'Ezekiel', 'Ezek', 'Eze', 'Ezk',
    'Daniel', 'Dan', 'Da', 'Dn',
    'Hosea', 'Hos', 'Ho',
    'Joel', 'Jl',
    'Amos', 'Am',
    'Obadiah', 'Obad', 'Ob',
    'Jonah', 'Jnh', 'Jon',
    'Micah', 'Mic', 'Mc',
    'Nahum', 'Nah', 'Na',
    'Habakkuk', 'Hab', 'Hb',
    'Zephaniah', 'Zeph', 'Zep', 'Zp',
    'Haggai', 'Hag', 'Hg',
    'Zechariah', 'Zech', 'Zec', 'Zc',
    'Malachi', 'Mal', 'Ml',
    'Matthew', 'Matt', 'Mt',
    'Mark', 'Mrk', 'Mar', 'Mk', 'Mr',
    'Luke', 'Luk', 'Lk',
    'John', 'Joh', 'Jhn', 'Jn',
    'Acts', 'Act', 'Ac',
    'Romans', 'Rom', 'Ro', 'Rm',
    '1st-Corinthians', '1-Cor', '1-Co', 'I-Cor', 'I-Co', '1Cor', '1Co', 'I-Corinthians', '1Corinthians', '1-Corinthians', 'First-Corinthians',
    '2nd-Corinthians', '2-Cor', '2-Co', 'II-Cor', 'II-Co', '2Cor', '2Co', 'II-Corinthians', '2Corinthians', '2-Corinthians', 'Second-Corinthians',
    'Galatians', 'Gal', 'Ga',
    'Ephesians', 'Eph', 'Ephes',
    'Philippians', 'Phil', 'Php', 'Pp',
    'Colossians', 'Col', 'Co',
    '1st-Thessalonians', '1-Thess', '1-Thes', '1-Th', 'I-Thessalonians', 'I-Thess', 'I-Thes', 'I-Th', '1Thessalonians', '1Thess', '1Thes', '1Th', '1-Thessalonians', '1st-Thess', 'First-Thessalonians', 'First-Thess',
    '2nd-Thessalonians', '2-Thess', '2-Thes', '2-Th', 'II-Thessalonians', 'II-Thess', 'II-Thes', 'II-Th', '2Thessalonians', '2Thess', '2Thes', '2Th', '2-Thessalonians', '2nd-Thess', 'Second-Thessalonians', 'Second-Thess',
    '1st-Timothy', '1-Tim', '1-Ti', 'I-Timothy', 'I-Tim', 'I-Ti', '1Timothy', '1Tim', '1Ti', '1-Timothy', '1st-Tim', 'First-Timothy', 'First-Tim',
    '2nd-Timothy', '2-Tim', '2-Ti', 'II-Timothy', 'II-Tim', 'II-Ti', '2Timothy', '2Tim', '2Ti', '2-Timothy', '2nd-Tim', 'Second-Timothy', 'Second-Tim',
    'Titus', 'Tit', 'Ti',
    'Philemon', 'Philem','Phm', 'Pm',
    'Hebrews', 'Heb',
    'James', 'Jas', 'Jm',
    '1st-Peter', '1-Pet', '1-Pe', '1-Pt', '1-P', 'I-Pet', 'I-Pt', 'I-Pe', '1Peter', '1Pet', '1Pe', '1Pt', '1P', 'I-Peter', '1-Peter', 'First-Peter',
    '2nd-Peter', '2-Pet', '2-Pe', '2-Pt', '2-P', 'II-Pet', 'II-Pt', 'II-Pe', '2Peter', '2Pet', '2Pe', '2Pt', '2P', 'II-Peter', '2-Peter', 'Second-Peter',
    '1st-John', '1-Jhn', '1-Jn', '1-J', '1John', '1Jhn', '1Joh', '1Jn', '1Jo', '1J', 'I-John', 'I-Jhn', 'I-Joh', 'I-Jn', 'I-Jo', '1-John', 'First-John',
    '2nd-John', '2-Jhn', '2-Jn', '2-J', '2John', '2Jhn', '2Joh', '2Jn', '2Jo', '2J', 'II-John', 'II-Jhn', 'II-Joh', 'II-Jn', 'II-Jo', '2-John', 'Second-John',
    '3rd-John', '3-Jhn', '3-Jn', '3-J', '3John', '3Jhn', '3Joh', '3Jn', '3Jo', '3J', 'III-John', 'III-Jhn', 'III-Joh', 'III-Jn', 'III-Jo', '3-John', 'Third-John',
    'Jude', 'Jud', 'Jd',
    'Revelation', 'Rev', 'Re', 'The-Revelation'
] 

key_to_shorted = {
    'Genesis': ('Gen', 'GEN', 'Ge', 'Gn'),
    'Exodus': ('Ex', 'Exo', 'Exod'),
    'Leviticus': ('Lev', 'Le', 'Lv'),
    'Numbers': ('Num', 'Nu', 'Nm', 'Nb'),
    'Deuteronomy': ('Deut', 'De', 'Dt'),
    'Joshua': ('Josh', 'Jos', 'Jsh'),
    'Judges': ('Judg', 'Jdg', 'Jdgs'),
    'Ruth': ('Rth', 'Ru'),
    '1st-Samuel': ('1-Sam', '1-Sa', '1-S', 'I-Sam', 'I-Sa', '1Sam', '1Sa', '1S', '1-Samuel', '1st-Sam', 'First-Samuel', 'First-Sam'),
    '2nd-Samuel': ('2-Sam', '2-Sa', '2-S', 'II-Sam', 'II-Sa', '2Sam', '2Sa', '2S', '2-Samuel', '2nd-Sam', 'Second-Samuel', 'Second-Sam'),
    '1st-Kings': ('1-Kgs', '1-Ki', '1Kgs', '1Kin', '1Ki', '1K', 'I-Kgs', 'I-Ki', '1-Kings', '1st-Kgs', 'First-Kings', 'First-Kgs'),
    '2nd-Kings': ('2 Kgs', '2-Ki', '2Kgs', '2Kin', '2Ki', '2K', 'II-Kgs', 'II-Ki', '2-Kings', '2nd-Kgs', 'Second-Kings', 'Second-Kgs'),
    '1st-Chronicles': ('1-Chron', '1-Chr', '1-Ch', '1Chron', '1Chr', '1Ch', 'I-Chron', 'I-Chr', 'I-Ch', '1-Chronicles', '1st-Chron', 'First-Chronicles', 'First-Chron'),
    '2nd-Chronicles': ('2-Chron', '2-Chr', '2-Ch', '2Chron', '2Chr', '2Ch', 'II-Chron', 'II-Chr', 'II-Ch', '2-Chronicles', '2nd-Chron', 'Second-Chronicles', 'Second-Chron'),
    'Ezra': ('Ezr', 'Ez'),
    'Nehemiah': ('Neh', 'Ne'),
    'Esther': ('Est', 'Esth', 'Es'),
    'Job': ('Jb'),
    'Psalms': ('Ps', 'Psalm', 'Pslm', 'Psa', 'Psm', 'Pss'),
    'Proverbs': ('Prov', 'Pro', 'Prv', 'Pr'),
    'Ecclesiastes': ('Eccle', 'Ecc', 'Ec', 'Qoh'),
    'Song-of-Solomon': ('Song', 'Song-of-Songs', 'SOS', 'So', 'Canticle-of-Canticles', 'Canticles', 'Cant'), 
    'Isaiah': ('Isa', 'Is'),
    'Jeremiah': ('Jer', 'Je', 'Jr'),
    'Lamentations': ('Lam', 'La'),
    'Ezekiel': ('Ezek', 'Eze', 'Ezk'),
    'Daniel': ('Dan', 'Da', 'Dn'),
    'Hosea': ('Hos', 'Ho'),
    'Joel': ('Jl'),
    'Amos': ('Am'),
    'Obadiah': ('Obad', 'Ob'),
    'Jonah': ('Jnh', 'Jon'),
    'Micah': ('Mic', 'Mc'),
    'Nahum': ('Nah', 'Na'),
    'Habakkuk': ('Hab', 'Hb'),
    'Zephaniah': ('Zeph', 'Zep', 'Zp'),
    'Haggai': ('Hag', 'Hg'),
    'Zechariah': ('Zech', 'Zec', 'Zc'),
    'Malachi': ('Mal', 'Ml'),
    'Matthew': ('Matt', 'Mt'),
    'Mark': ('Mrk', 'Mar', 'Mk', 'Mr'),
    'Luke': ('Luk', 'Lk'),
    'John': ('Joh', 'Jhn', 'Jn'),
    'Acts': ('Act', 'Ac'),
    'Romans': ('Rom', 'Ro', 'Rm'),
    '1st-Corinthians': ('1-Cor', '1-Co', 'I-Cor', 'I-Co', '1Cor', '1Co', 'I-Corinthians', '1Corinthians', '1-Corinthians', 'First-Corinthians'),
    '2nd-Corinthians': ('2-Cor', '2-Co', 'II-Cor', 'II-Co', '2Cor', '2Co', 'II-Corinthians', '2Corinthians', '2-Corinthians', 'Second-Corinthians'),
    'Galatians': ('Gal', 'Ga'),
    'Ephesians': ('Eph', 'Ephes'),
    'Philippians': ('Phil', 'Php', 'Pp'),
    'Colossians': ('Col', 'Co'),
    '1st-Thessalonians': ('1-Thess', '1-Thes', '1-Th', 'I-Thessalonians', 'I-Thess', 'I-Thes', 'I-Th', '1Thessalonians', '1Thess', '1Thes', '1Th', '1-Thessalonians', '1st-Thess', 'First-Thessalonians', 'First-Thess'),
    '2nd-Thessalonians': ('2-Thess', '2-Thes', '2-Th', 'II-Thessalonians', 'II-Thess', 'II-Thes', 'II-Th', '2Thessalonians', '2Thess', '2Thes', '2Th', '2-Thessalonians', '2nd-Thess', 'Second-Thessalonians', 'Second-Thess'),
    '1st-Timothy': ('1-Tim', '1-Ti', 'I-Timothy', 'I-Tim', 'I-Ti', '1Timothy', '1Tim', '1Ti', '1-Timothy', '1st-Tim', 'First-Timothy', 'First-Tim'),
    '2nd-Timothy': ('2-Tim', '2-Ti', 'II-Timothy', 'II-Tim', 'II-Ti', '2Timothy', '2Tim', '2Ti', '2-Timothy', '2nd-Tim', 'Second-Timothy', 'Second-Tim'),
    'Titus': ('Tit', 'Ti'),
    'Philemon': ('Philem','Phm', 'Pm'),
    'Hebrews': ('Heb'),
    'James': ('Jas', 'Jm'),
    '1st-Peter': ('1-Pet', '1-Pe', '1-Pt', '1-P', 'I-Pet', 'I-Pt', 'I-Pe', '1Peter', '1Pet', '1Pe', '1Pt', '1P', 'I-Peter', '1-Peter', 'First-Peter'),
    '2nd-Peter': ('2-Pet', '2-Pe', '2-Pt', '2-P', 'II-Pet', 'II-Pt', 'II-Pe', '2Peter', '2Pet', '2Pe', '2Pt', '2P', 'II-Peter', '2-Peter', 'Second-Peter'),
    '1st-John': ('1-Jhn', '1-Jn', '1-J', '1John', '1Jhn', '1Joh', '1Jn', '1Jo', '1J', 'I-John', 'I-Jhn', 'I-Joh', 'I-Jn', 'I-Jo', '1-John', 'First-John'),
    '2nd-John': ('2-Jhn', '2-Jn', '2-J', '2John', '2Jhn', '2Joh', '2Jn', '2Jo', '2J', 'II-John', 'II-Jhn', 'II-Joh', 'II-Jn', 'II-Jo', '2-John', 'Second-John'),
    '3rd-John': ('3-Jhn', '3-Jn', '3-J', '3John', '3Jhn', '3Joh', '3Jn', '3Jo', '3J', 'III-John', 'III-Jhn', 'III-Joh', 'III-Jn', 'III-Jo', '3-John', 'Third-John'),
    'Jude': ('Jud', 'Jd'),
    'Revelation': ('Rev', 'Re', 'The-Revelation')
}


shorted_to_key = {}
for key, shorted_tuple in key_to_shorted.items():
    for shorted in shorted_tuple:
        shorted_to_key[shorted] = key

chapters_of_book = {
    'Genesis':50,
    'Exodus':40,
    'Leviticus':27,
    'Numbers':36,
    'Deuteronomy':34,
    'Joshua':24,
    'Judges':21,
    'Ruth':4,
    '1st-Samuel':31,
    '2nd-Samuel':24,
    '1st-Kings':22,
    '2nd-Kings':25,
    '1st-Chronicles':29,
    '2nd-Chronicles':36,
    'Ezra':10,
    'Nehemiah':13,
    'Esther':10,
    'Job':42,
    'Psalms':150,
    'Proverbs':31,
    'Ecclesiastes':12,
    'Song-of-Solomon':8,
    'Isaiah':66,
    'Jeremiah':52,
    'Lamentations':5,
    'Ezekiel':48,
    'Daniel':12,
    'Hosea':14,
    'Joel':3,
    'Amos':9,
    'Obadiah':1,
    'Jonah':4,
    'Micah':7,
    'Nahum':3,
    'Habakkuk':3,
    'Zephaniah':3,
    'Haggai':2,
    'Zechariah':14,
    'Malachi':4,
    'Matthew':28,
    'Mark':16,
    'Luke':24,
    'John':21,
    'Acts':28,
    'Romans':16,
    '1st Corinthians':16,
    '2nd Corinthians':13,
    'Galatians':6,
    'Ephesians':6,
    'Philippians':4,
    'Colossians':4,
    '1st-Thessalonians':5,
    '2nd-Thessalonians':3,
    '1st-Timothy':6,
    '2nd-Timothy':4,
    'Titus':3,
    'Philemon':1,
    'Hebrews':13,
    'James':5,
    '1st-Peter':5,
    '2nd-Peter':3,
    '1st-John':5,
    '2nd-John':1,
    '3rd-John':1,
    'Jude':1,
    'Revelation':22
    }

